openapi: 3.0.1
info:
  title: SPOLookUp
  description: Import from "SPOLookUp" Function App
  version: '1.0'
servers:
  - url: https://ent-spo-api.azure-api.net/SPOLookUp
paths:
  /SharePointLookup:
    get:
      operationId: getSiteDetails
      summary: Get SharePoint Site Information
      description: This API retrieves information about SharePoint sites.
      parameters:
        - in: query
          name: url
          schema:
            type: string
          description: Provide the SharePoint site URL to retrieve information.
      responses:
        '200':
          description: 
components:
  schemas:
    SiteInfo:
      type: object
      properties:
        info:
          type: string
          description: Site details.